baseURL = "https://blog.thanh-vo.com/"

title = "Hoang Thanh VO - Cloud and Infrastructure blog"
theme = "hello-friend"
languageCode = "en-us"

[params]
    defaultTheme = "light"
    contentTypeName = "posts"
    showMenuItems = 2
    showReadingTime = true

[languages]
    [languages.en]
        title = "Hoang Thanh VO"
        subtitle = "Cloud and Infrastructure blog"
        keywords = "blog, information technology, engineering, cloud computing, infrastructure as code, devops"
        copyright = "¬© 2022 | written with ‚ô•Ô∏è"
        menuMore = "Show more"
        writtenBy = "Written by"
        readMore = "Read more"
        readOtherPosts = "Read other posts"
        newerPosts = "Newer posts"
        olderPosts = "Older posts"
        minuteReadingTime = "min read"
        dateFormatSingle = "2006-01-02"
        dateFormatList = "2006-01-02"
        lastModDisplay = ""

    [languages.en.params.logo]
        logoText = "Hoang Thanh VO üë®üèª‚Äçüíª"
        logoHomeLink = "https://blog.thanh-vo.com"

    [languages.en.menu]
        [[languages.en.menu.main]]
            identifier = "about"
            name = "About"
            url = "/about"
